// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/14/2025, 3:32:33 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/caddy/Desktop/StudentProgressTracker/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/caddy/Desktop/StudentProgressTracker/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/caddy/Desktop/StudentProgressTracker/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/caddy/Desktop/StudentProgressTracker/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/caddy/Desktop/StudentProgressTracker/plugins/**/*.{js,ts,mjs}","/Users/caddy/Desktop/StudentProgressTracker/composables/**/*.{js,ts,mjs}","/Users/caddy/Desktop/StudentProgressTracker/utils/**/*.{js,ts,mjs}","/Users/caddy/Desktop/StudentProgressTracker/pages/index.vue","/Users/caddy/Desktop/StudentProgressTracker/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/caddy/Desktop/StudentProgressTracker/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/caddy/Desktop/StudentProgressTracker/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;